package view;

import controller.ItemController;
import controller.MainController;
import model.Category;
import model.Item;

import javax.swing.*;
import java.awt.*;

public class AddItem {

    public static void show() {
        // --- Setup Dialog ---
        JDialog dialog = new JDialog((Frame) null, "Add New Item", true);
        dialog.setSize(800, 650);
        dialog.setLocationRelativeTo(null);
        dialog.setLayout(new BorderLayout());

        JPanel mainPanel = new JPanel(new GridLayout(1, 2));

        // --- LEFT PANEL (Form) ---
        JPanel leftPanel = new JPanel(null);
        leftPanel.setBackground(new Color(225, 238, 245));

        // Header
        JPanel header = new JPanel(null);
        header.setBackground(new Color(15, 70, 120));
        header.setBounds(0, 0, 400, 80);

        JLabel lblTitle = new JLabel("  Add New Item");
        lblTitle.setFont(new Font("Arial", Font.BOLD, 30));
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setBounds(20, 20, 350, 40);
        header.add(lblTitle);
        leftPanel.add(header);

        // Name Field
        JLabel lblName = new JLabel("Item Name");
        lblName.setFont(new Font("Arial", Font.PLAIN, 20));
        lblName.setBounds(50, 120, 200, 25);
        leftPanel.add(lblName);

        JTextField txtName = createField();
        txtName.setBounds(50, 150, 300, 35);
        leftPanel.add(txtName);

        // Price Field
        JLabel lblPrice = new JLabel("Price");
        lblPrice.setFont(new Font("Arial", Font.PLAIN, 20));
        lblPrice.setBounds(50, 200, 200, 25);
        leftPanel.add(lblPrice);

        JTextField txtPrice = createField();
        txtPrice.setBounds(50, 230, 300, 35);
        leftPanel.add(txtPrice);

        // Quantity Field
        JLabel lblQty = new JLabel("Quantity");
        lblQty.setFont(new Font("Arial", Font.PLAIN, 20));
        lblQty.setBounds(50, 280, 200, 25);
        leftPanel.add(lblQty);

        JTextField txtQty = createField();
        txtQty.setBounds(50, 310, 300, 35);
        leftPanel.add(txtQty);

        // Min Threshold Field
        JLabel lblMin = new JLabel("Min Threshold");
        lblMin.setFont(new Font("Arial", Font.PLAIN, 20));
        lblMin.setBounds(50, 360, 200, 25);
        leftPanel.add(lblMin);

        JTextField txtMin = createField();
        txtMin.setBounds(50, 390, 300, 35);
        leftPanel.add(txtMin);

        // Category Checkboxes
        JLabel lblCategory = new JLabel("Category");
        lblCategory.setFont(new Font("Arial", Font.PLAIN, 20));
        lblCategory.setBounds(50, 440, 200, 25);
        leftPanel.add(lblCategory);

        JCheckBox chkFabric = new JCheckBox("Fabric");
        JCheckBox chkThread = new JCheckBox("Thread");
        JCheckBox chkButton = new JCheckBox("Button");
        JCheckBox chkZipper = new JCheckBox("Zipper");
        JCheckBox chkLeather = new JCheckBox("Leather");

        JCheckBox[] boxes = {chkFabric, chkThread, chkButton, chkZipper, chkLeather};
        int x = 50, y = 470;

        ButtonGroup categoryGroup = new ButtonGroup();
        for (JCheckBox box : boxes) {
            box.setFont(new Font("Arial", Font.PLAIN, 16));
            box.setBounds(x, y, 100, 25);
            box.setOpaque(false);
            categoryGroup.add(box);
            leftPanel.add(box);
            x += 100;
            if (x > 300) { x = 50; y += 30; }
        }

        // Add Button
        JButton btnAdd = new JButton("Add Item");
        btnAdd.setBounds(50, 540, 300, 45);
        btnAdd.setBackground(new Color(0xF7941D));
        btnAdd.setForeground(Color.WHITE);
        btnAdd.setFont(new Font("Arial", Font.BOLD, 16));
        btnAdd.setFocusable(false);
        leftPanel.add(btnAdd);

        // --- LOGIC ---
        btnAdd.addActionListener(e -> {
            try {
                String name = txtName.getText().trim();
                if (name.isEmpty()) throw new IllegalArgumentException("Name is required");

                double price = Double.parseDouble(txtPrice.getText().trim());
                int quantity = Integer.parseInt(txtQty.getText().trim());
                int minThreshold = Integer.parseInt(txtMin.getText().trim());

                String categoryStr = null;
                if (chkFabric.isSelected()) categoryStr = "FABRIC";
                else if (chkThread.isSelected()) categoryStr = "THREAD";
                else if (chkButton.isSelected()) categoryStr = "BUTTON";
                else if (chkZipper.isSelected()) categoryStr = "ZIPPER";
                else if (chkLeather.isSelected()) categoryStr = "LEATHER";

                if (categoryStr == null) throw new IllegalArgumentException("Please select a category");

                // Create Item (ID auto-generated by constructor)
                Item newItem = new Item(name, categoryStr, price, quantity, minThreshold);

                // Add to Controller
                ItemController controller = new ItemController();
                controller.addItem(newItem);

                JOptionPane.showMessageDialog(dialog, "Item added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                dialog.dispose();

                // Refresh View
                JFrame mainFrame = MainController.getFrame();
                if (mainFrame != null) {
                    Storage.storage(mainFrame, DashBoard.getLeftPanel());
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Please enter valid numbers for Price, Qty, and Min.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // --- RIGHT PANEL (Image) ---
        JPanel rightPanel = new JPanel(new BorderLayout());
        rightPanel.setBackground(Color.WHITE);

        JPanel headerRight = new JPanel(null);
        headerRight.setBackground(new Color(15, 70, 120));
        headerRight.setPreferredSize(new Dimension(400, 80));
        rightPanel.add(headerRight, BorderLayout.NORTH);

        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(JLabel.CENTER);
        // Using standard item image from your assets
        ImageIcon originalIcon = new ImageIcon("assets/itemadd.png");
        Image scaled = originalIcon.getImage().getScaledInstance(300, 300, Image.SCALE_DEFAULT);
        imageLabel.setIcon(new ImageIcon(scaled));

        rightPanel.add(imageLabel, BorderLayout.CENTER);

        mainPanel.add(leftPanel);
        mainPanel.add(rightPanel);
        dialog.add(mainPanel);
        dialog.setVisible(true);
    }

    private static JTextField createField() {
        JTextField field = new JTextField();
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200)),
                BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        return field;
    }
}
